version: "3.3"

services:
  db:
    container_name: cars-db
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - .env

  cars-api: &cars
    container_name: cars-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c " python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - ./tests:/app/tests
      - ./data/media:/public/media
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  postgres_volume: